/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Meuro
 * ammdb  -  ammdb
 */
drop table adesione
drop table postgruppo;
drop table gruppo;
drop table post;
drop table bacheca;
drop table utente;



CREATE TABLE utente(
    id_utente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(256) NOT NULL,
    password VARCHAR(256)NOT NULL,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    anno VARCHAR(256),
    frase VARCHAR(256),
    urlfoto VARCHAR(256),
    email VARCHAR(256)
);

CREATE TABLE bacheca(
    id_bacheca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario INTEGER,
    FOREIGN KEY (proprietario)REFERENCES utente(id_utente)
);


CREATE TABLE post(
    id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cont_testo VARCHAR(1024),
    tipo_all INTEGER,
    cont_all VARCHAR(256),
    autore INTEGER,
    bacheca INTEGER,
    FOREIGN KEY (autore) REFERENCES utente(id_utente),
    FOREIGN KEY (bacheca)REFERENCES bacheca(id_bacheca)
);

CREATE TABLE gruppo(
    id_gruppo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(30) NOT NULL
   );


CREATE TABLE postgruppo(
    id_post INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cont_testo VARCHAR(1024),
    tipo_all INTEGER,
    cont_all VARCHAR(256),
    autore INTEGER,
    bac_gruppo INTEGER,
    FOREIGN KEY (autore) REFERENCES utente(id_utente),
    FOREIGN KEY (bac_gruppo)REFERENCES gruppo(id_gruppo)
);

CREATE TABLE adesione(
    partecipante INTEGER,
    gruppo INTEGER,
    FOREIGN KEY (partecipante) REFERENCES utente(id_utente),
    FOREIGN KEY (gruppo)REFERENCES gruppo(id_gruppo)
    PRIMARY KEY(partecipante,gruppo)
);



/* utente #1 amministratore*/

/* Popolamento utente*/
INSERT INTO utente VALUES 
(default,'admin','admin',null,null,null,null,null,null),
(default,'giollone','petoloso','massimo','zedda','1970-10-20','Rotonde a strupiarura!!','img/nerd1.jpg','giolloso70@email.it'),
(default,'nvidio','minecraft','antonello','lai',null,'Agli zingari le case','img/nerd2.jpg',null),
(default,'nationalgeonerding','bbth',null,null,null,null,'img/nerd3.jpg',null);


INSERT INTO bacheca VALUES
(default,1),
(default,2),
(default,3);

INSERT INTO post VALUES
(default,'Oggi è una bellissima giornata di sole!!XDXDXD',0,null,2,1),
(default,'Ho passato la notte a giocarci!LOL che belloXDXD',1,'img/mcrft.jpg',3,1),
(default,
'WOW!Uscire a comprare il pane mi ha stancato troppo,passerò il pomeriggio a guardareThe Big Bang Theory...SUPER WOW',
2,'https://eurostreaming.club/the-big-bang-theory-40/',4,2);

INSERT INTO gruppo values
(default,'I 10 Comandamenti di Tesla '),
(default,'Tom s HW & Jerry s SW');

INSERT INTO adesione VALUES
(2,1),
(3,1),
(4,2);





